sudo: false
language: ruby
env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
rvm:
    - 2.0
    - 2.1
before_install:
    - npm install -g bower
    - bower install
script:
    - bundle exec jekyll build
    - bundle exec htmlproof ./_site
