#
# Site settings
#

description: "Site description"
title: "Site Title"

#
# Author
#

author: "Site Author"
email: "email@example.com"
github_username:  "jekyll"
twitter_username: "jekyllrb"

#
# Build settings
#

gems:
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jemoji
exclude:
    - _vendor
    - bower.json
    - Gemfile
    - Gemfile.lock
    - Makefile
    - README.md
    - vendor
markdown: kramdown
permalink: pretty
safe: true
sass:
    sass_dir: _vendor/foundation/scss
    style: :compressed
