#
# Site settings
#

description: Site description
title: Site Title

#
# Author
#

author: John Doe
email: johndoe@example.com

#
# Build settings
#

gems:
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jemoji
exclude:
    - _vendor
    - bower.json
    - CHANGELOG.md
    - Gemfile
    - Gemfile.lock
    - Makefile
    - README.md
    - vendor
markdown: kramdown
permalink: pretty
safe: true
sass:
    sass_dir: _vendor/foundation/scss
    style: :compressed

#
# Defaults
#

defaults:
  - scope:
        path: ""
    values:
        layout: default
