#
# Site settings
#

description: Site description
title: Site Title

#
# Author
#

author: John Doe
email: johndoe@example.com

#
# Build settings
#

gems:
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jemoji
exclude:
    - bower.json
    - Brocfile.js
    - CHANGELOG.md
    - CONTRIBUTING.md
    - Gemfile
    - Gemfile.lock
    - LICENSE.txt
    - Makefile
    - node_modules
    - package.json
    - README.md
markdown: kramdown
permalink: pretty
safe: true

#
# Defaults
#

defaults:
  - scope:
        path: ""
    values:
        layout: default
